stages:
  - check
  - build
  - deploy

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

sonar-check:
  stage: check
  image: maven:3.8.3-openjdk-17
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    # 1. 'verify' roda os testes e o JaCoCo gera o relatório.
    # 2. 'sonar:sonar' agora sabe onde ler esse relatório.
    - mvn verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
  only:
    - main

build:
  stage: build
  image: maven:3.8.3-openjdk-17
  artifacts:
    paths:
      - target/
  script:
    - mvn clean verify -Dsonar.skip=true -DskipTests=true install
  only:
    - main

aws-deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
   - aws deploy push --application-name unirio-pm-projetos-base --s3-location s3://unirio-pm-projetos-base/projeto-base-spring-boot.zip --source .
   - aws deploy create-deployment --application-name unirio-pm-projetos-base --deployment-group-name projeto-base-spring-boot --s3-location bucket=unirio-pm-projetos-base,key=projeto-base-spring-boot.zip,bundleType=zip
  only:
    - main
  dependencies: 
    - build
