name: Build e An치lise SonarCloud

on:
  push:
    branches:
      - main  # Ou o nome da sua branch principal
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build e An치lise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necess치rio para o Sonar
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Usa Java 17 para RODAR o build
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build, Teste e An치lise Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token do GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Token do Sonar 
        run: >
          mvn -B clean verify sonar:sonar 
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml